name: Generate Snake Animation

on:
  schedule:
    # Runs at 12:00 AM UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create the output directory
        run: mkdir -p dist

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Kaikoo00
          output: dist/snake.svg

      - name: List files in the dist directory
        run: ls -R dist

      - name: Push the animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
